Repository semuconsulting/pyubx2, pull requests merged in 2024-09, with the labels that each got.

#158 Rc 1.2.45
  .vscode/settings.json
  RELEASE_NOTES.md
  pyproject.toml
  src/pyubx2/_version.py
  src/pyubx2/ubxtypes_core.py
  src/pyubx2/ubxtypes_get.py
  src/pyubx2/ubxtypes_poll.py
  src/pyubx2/ubxvariants.py
  tests/pygpsdata-SEC.log
  tests/test_stream.py
Labels: bug, enhancement

#157 Fix structure of `SEC-SIGLOG`
  src/pyubx2/ubxtypes_get.py
Labels: bug

#159 update to v1.2.46
  .vscode/settings.json
  RELEASE_NOTES.md
  pyproject.toml
  src/pyubx2/_version.py
Labels: enhancement
